### ISSUE TITLE
Synchronous flow for login

### ISSUE THREAD

**Issue by bilogic** [realcoloride/CoolWebSocketClient#2]
Aim: I need to log on to a Google Protobuf websocket server with credentials first, and until I'm logged on, there should be no other messages being sent. Since all received messages are passed to `OnMessage`, and I wrote my message handler inside.

Problem: I have to write gymnastic code in `OnMessage` handler to check if I'm logged on etc, and I can't get the code to play nicely with async/await

Would be great it there was a clean way/example to a very synchronous operation like logon.

**Comment by realcoloride** [comment]
Hello, could you provide me an example for me to understand better?

**Comment by bilogic** [comment]
It is probably easier to describe the problem in protocol form. This is just an example to illustrate the issue, I understand all the security issues arising from such an approach.

My question would be, how do I make the websocket "wait" until USERNAME and PASSWORD are ok?

```
# --> send
# <-- receive

# correct
--> USERNAME
<-- USERNAME OK
--> PASSWORD
<-- PASSWORD OK
--> REQ1
--> REQ2
--> REQ3
--> REQ4
<-- ANS1
<-- ANS2
<-- ANS3
<-- ANS4

# issue, PASSWORD, REQ1 to REQ4 are ignored because I'm not logged on yet
--> USERNAME
--> PASSWORD
--> REQ1
--> REQ2
--> REQ3
--> REQ4
<-- USERNAME OK
```

**Comment by realcoloride** [comment]
Hey there, you can use `TaskCompletionSource` and `Task`s to resolve what you meant right here using asynchronous calls.
`Task.WhenAny` and `TaskCompletionSource?.TrySetResult(receivedMessage)` should help.

I'm aware that this is probably not the best solution out here, but you can automate this one I'm pretty sure.

Let me know if you need a code example.

Cheers

**Comment by bilogic** [comment]
Hi, 

Yes, an example will be very helpful. I'm using a mutex to overcome it right now, but the code is a bit ugly.

My main area of confusion is how to mix the use of `events` with `await`/`async`.
So I'm parsing my messages in ws_OnMessage, i.e. it is the one who figures out if `PASSWORD OK` has been received



And I'm actually writing in VB.NET.

Thank you!

**Comment by realcoloride** [comment]
Hello there. I am not familiar with Visual Basic, but I can definitely help out with an example of automation.

```cs

        private async Task WaitForResponse(string message, Func<string, bool> conditionCallback)
        {
            TaskCompletionSource<bool> responseAcknowledger = new();

            // define a temporary handler method
            void ResponseHandler(string receivedMessage)
            {
                // check if the received message meets the condition
                if (conditionCallback(receivedMessage))
                    responseAcknowledger.TrySetResult(true);
            }

            // subscribe to the WebSocket's message handler
            websocket.OnMessageReceived += ResponseHandler;

            try
            {
                // send the message and wait for the response to match the condition
                await websocket.Send(message);

                // await the TaskCompletionSource task, which completes when the condition is met
                await responseAcknowledger.Task;
            }
            finally
            {
                // then we can unsubscribe from the event to avoid memory leaks
                websocket.OnMessageReceived -= ResponseHandler;
            }
        }
```

Example usage:

```cs
await WaitForResponse("USERNAME john_doe", packet => packet == "USERNAME OK");
```

Here I make an asynchronous function that checks if a condition is true the string for input but the pseudo `packet => packet == condition` is an example, however, feel free to adjust them to your need.

You subscribe temporarily to the message sent event, you check if the condition is correct, and you are good to go.

The first element could be what you sent and second would be what condition breaks the asynchronous promise.
There are also numerous ways to tackle this, but I believe this one is the most straightforward to automate.

Hopefully this example code can help you out, and if you have any other questions, feel free to reach out.

I will close the issue now since it is not a related problem to the package but rather a usage problem, but it will not be locked and you are free to re-open an issue if another problem arises.

Cheers
